"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcZ_srJr8x8AqoFvvh7CccxHVC9yiSgb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/insurance_data.csv")
data



b=data.isnull().sum()
print(b)

col_list=list(data.columns)
print(col_list)

for x in col_list:
    if data[x].dtype == "object":
        data[x].fillna(data[x].mode()[0], inplace=True)
    else:
        data[x].fillna(data[x].mean(), inplace=True)

a = data.isnull().sum()
print(a)

plt.boxplot(data["Anual_Salary"])
plt.xlabel("annualsalary")
plt.ylabel("count")
plt.show()

"""finding outier in every coloumns

"""

for x in col_list:
  if data[x].dtypes=="object":
    continue
  plt.boxplot(data[x])
  plt.xlabel(x)
  plt.ylabel("count")
  plt.show()

"""now we need to deal with the outliers in the dataset

"""

for x in col_list:
    if data[x].dtype == "object" or x == "changes":
        continue

    q1 = data[x].quantile(0.25)
    q3 = data[x].quantile(0.75)

    iqr = q3 - q1

    upper = q3 + (1.5 * iqr)
    lower = q1 - (1.5 * iqr)

    data[x] = np.where(
        data[x] > upper,
        upper,
        np.where(data[x] < lower, lower, data[x])
    )


for x in col_list:
    if data[x].dtype == "object" or x == "changes":
        continue

    plt.boxplot(data[x])
    plt.xlabel(x)
    plt.ylabel("Value")
    plt.show()

"""by using label-ecoding convert my catagorical coloumns inti numerical coloumns

"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for x in col_list:
  if data[x].dtype=='object':
    data[x]=le.fit_transform(data[x])
data

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x=data.iloc[:,:12]
y=data.iloc[:,-1]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)
print(x)

print(y)

print(x_train)

print(x_test)

print(y_train)

print(y_test)

Linear_model = LinearRegression()
Linear_model.fit(x_train, y_train)

LinearRegression_model = LinearRegression()

LinearRegression_model.fit(x_train, y_train)

model_predicted = LinearRegression_model.predict(x_test)

print(model_predicted)

print(y)

from sklearn.metrics import r2_score

r2_accuracy = r2_score(y_test, model_predicted)

print(r2_accuracy * 100)

sns.regplot(x=model_predicted,y=y_test)
plt.xlabel("modelpredicted ")
plt.ylabel("y_test")
plt.title("modelpredicted vs y_test ")
plt.grid(True)
plt.show()